# Generated by Django 5.0.7 on 2024-08-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("research_area", models.CharField(max_length=500)),
                ("publications", models.TextField()),
                ("education", models.TextField()),
                ("teaching_area", models.TextField()),
            ],
        ),
    ]
